"""
Decision Engine Data Models and Enums for BhoomiMitra AI.
Defines input payloads, decision outcomes, risk tiers, and response structures.
"""

from dataclasses import dataclass, field
from enum import Enum
from typing import List, Optional


class DecisionType(str, Enum):
    """Decision outcomes produced by the Decision Engine."""
    ANSWER = "ANSWER"
    ASK_CLARIFICATION = "ASK_CLARIFICATION"
    SAFE_FALLBACK = "SAFE_FALLBACK"
    ESCALATE = "ESCALATE"


class RiskLevel(str, Enum):
    """Assessed risk level of farmer query and recommended advisory."""
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"


@dataclass
class FarmerInput:
    """Input parameters provided by or extracted from the farmer's interaction."""
    message: str
    crop: Optional[str] = None
    growth_stage: Optional[str] = None
    problem: Optional[str] = None
    location: Optional[str] = None


@dataclass
class Decision:
    """Final decision output generated by the AI Decision Engine."""
    decision_type: DecisionType
    risk_level: RiskLevel
    response: str
    reasons: List[str] = field(default_factory=list)
    requires_human_review: bool = False


@dataclass
class ResponseValidationResult:
    """Outcome of validating generated AI responses for agricultural safety."""
    is_safe: bool
    violations: List[str] = field(default_factory=list)
    reasons: List[str] = field(default_factory=list)
    safe_response: str = ""

