"""initial schema

Revision ID: 001_initial_schema
Revises: 
Create Date: 2026-07-11 14:10:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '001_initial_schema'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('farmers',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('preferred_language', sa.String(length=10), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_farmers_phone_number'), 'farmers', ['phone_number'], unique=True)
    
    op.create_table('farmer_profiles',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('farmer_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('district', sa.String(length=50), nullable=True),
    sa.Column('current_crop', sa.String(length=100), nullable=True),
    sa.Column('land_size_acres', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('farmer_id')
    )
    op.create_index(op.f('ix_farmer_profiles_district'), 'farmer_profiles', ['district'], unique=False)
    op.create_index(op.f('ix_farmer_profiles_state'), 'farmer_profiles', ['state'], unique=False)
    
    op.create_table('conversations',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('farmer_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('message_id', sa.String(length=100), nullable=False),
    sa.Column('user_message', sa.Text(), nullable=True),
    sa.Column('user_message_type', sa.String(length=20), nullable=True),
    sa.Column('ai_response', sa.Text(), nullable=True),
    sa.Column('intent', sa.String(length=50), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    
    # New Outbound Tracking Fields added in this migration
    sa.Column('outbound_message_id', sa.String(length=100), nullable=True),
    sa.Column('delivery_status', sa.String(length=20), nullable=True),
    
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id')
    )
    op.create_index(op.f('ix_conversations_created_at'), 'conversations', ['created_at'], unique=False)
    op.create_index(op.f('ix_conversations_farmer_id'), 'conversations', ['farmer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conversations_farmer_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_created_at'), table_name='conversations')
    op.drop_table('conversations')
    
    op.drop_index(op.f('ix_farmer_profiles_state'), table_name='farmer_profiles')
    op.drop_index(op.f('ix_farmer_profiles_district'), table_name='farmer_profiles')
    op.drop_table('farmer_profiles')
    
    op.drop_index(op.f('ix_farmers_phone_number'), table_name='farmers')
    op.drop_table('farmers')
    # ### end Alembic commands ###
