"""add crop_health table

Revision ID: 8e17dcd6d1dc
Revises: 4d2af5e4c980
Create Date: 2026-07-11 20:13:18.992873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e17dcd6d1dc'
down_revision = '4d2af5e4c980'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crop_health',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('crop_id', sa.UUID(), nullable=False),
    sa.Column('farmer_id', sa.UUID(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('symptoms', sa.Text(), nullable=False),
    sa.Column('disease_name', sa.String(length=100), nullable=True),
    sa.Column('diagnosis_result', sa.Text(), nullable=False),
    sa.Column('treatment_recommendation', sa.Text(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['crop_id'], ['crops.id'], ),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crop_health_crop_id'), 'crop_health', ['crop_id'], unique=False)
    op.create_index(op.f('ix_crop_health_farmer_id'), 'crop_health', ['farmer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_crop_health_farmer_id'), table_name='crop_health')
    op.drop_index(op.f('ix_crop_health_crop_id'), table_name='crop_health')
    op.drop_table('crop_health')
    # ### end Alembic commands ###
